name: Deploy Production Timro Ticket API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            PROJECT_DIR="/var/www/api.thebandbtech.com"
            REPO_URL="git@github.com:BandBTech/bandbtech_backend.git"

            if [ -d "$PROJECT_DIR/.git" ]; then
              echo "üõ† Directory exists with git repo - Pulling latest code"
              cd $PROJECT_DIR
              GIT_SSH_COMMAND="ssh -i ~/.ssh/bnbackend_ed25519" git reset --hard
              GIT_SSH_COMMAND="ssh -i ~/.ssh/bnbackend_ed25519" git pull origin staging
            else
              echo "üìÅ Directory empty or no git repo - Cloning repository"
              rm -rf $PROJECT_DIR
              GIT_SSH_COMMAND="ssh -i ~/.ssh/bnbackend_ed25519" git clone -b staging $REPO_URL $PROJECT_DIR
              cd $PROJECT_DIR
            fi

            echo "üßπ Cleaning up old containers"
            docker compose down

            echo "üì¶ Rebuilding Docker image"
            docker-compose up -d --build

            echo "‚úÖ Deployment complete"
